name: Golang CI

on:
    push:
        branches: [main]
    pull_request:

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.22.x"

            - name: Display Go version
              run: go version

            - name: Get dependencies
              run: go get ./...

            - name: Build
              run: go build -v ./...

            - name: Run unit tests
              run: go test -v ./...
